// Curated exact-ID test/final-model pairs. See data/audio-curation.json.
const demoSamples = {
  "hyena": {
    "name": "Spotted hyena",
    "samples": [
      {
        "id": "hyena-whoop-172",
        "label": "Whoop",
        "prompt": "The animal sound comes from a spotted hyena as it seeks distant clan contact.",
        "realAudio": "audio/hyena-whoop-172-real.wav",
        "generatedAudio": "audio/hyena-whoop-172-generated.wav",
        "realSpectrogram": "spectrograms/hyena-whoop-172-real.png",
        "generatedSpectrogram": "spectrograms/hyena-whoop-172-generated.png",
        "duration": 1.4,
        "realDuration": 1.4,
        "generatedDuration": 1.4,
        "source": "hyena/whoop/whoop_sample_172.wav",
        "playbackGainDb": 18.488
      },
      {
        "id": "hyena-alarm-rumble-22",
        "label": "Alarm rumble",
        "prompt": "A vocalization occurs as a spotted hyena alerts clanmates nearby.",
        "realAudio": "audio/hyena-alarm-rumble-22-real.wav",
        "generatedAudio": "audio/hyena-alarm-rumble-22-generated.wav",
        "realSpectrogram": "spectrograms/hyena-alarm-rumble-22-real.png",
        "generatedSpectrogram": "spectrograms/hyena-alarm-rumble-22-generated.png",
        "duration": 1.72,
        "realDuration": 1.72,
        "generatedDuration": 1.72,
        "source": "hyena/alarm_rumble/alarm_rumble_sample_22.wav",
        "playbackGainDb": 23.31
      },
      {
        "id": "hyena-giggle-28",
        "label": "Giggle",
        "prompt": "A vocalization comes from a spotted hyena when it reacts during conflict.",
        "realAudio": "audio/hyena-giggle-28-real.wav",
        "generatedAudio": "audio/hyena-giggle-28-generated.wav",
        "realSpectrogram": "spectrograms/hyena-giggle-28-real.png",
        "generatedSpectrogram": "spectrograms/hyena-giggle-28-generated.png",
        "duration": 0.35,
        "realDuration": 0.35,
        "generatedDuration": 0.35,
        "source": "hyena/giggle/giggle_sample_28.wav",
        "playbackGainDb": 17.184
      },
      {
        "id": "hyena-groan-3647",
        "label": "Groan",
        "prompt": "A vocalization occurs when a spotted hyena engages in affiliative contact.",
        "realAudio": "audio/hyena-groan-3647-real.wav",
        "generatedAudio": "audio/hyena-groan-3647-generated.wav",
        "realSpectrogram": "spectrograms/hyena-groan-3647-real.png",
        "generatedSpectrogram": "spectrograms/hyena-groan-3647-generated.png",
        "duration": 0.93,
        "realDuration": 0.93,
        "generatedDuration": 0.93,
        "source": "hyena/groan/groan_sample_3647.wav",
        "playbackGainDb": 20.749
      },
      {
        "id": "hyena-growl-23",
        "label": "Growl",
        "prompt": "The audible sound is heard from an attacked spotted hyena while it is bitten by another animal.",
        "realAudio": "audio/hyena-growl-23-real.wav",
        "generatedAudio": "audio/hyena-growl-23-generated.wav",
        "realSpectrogram": "spectrograms/hyena-growl-23-real.png",
        "generatedSpectrogram": "spectrograms/hyena-growl-23-generated.png",
        "duration": 0.28,
        "realDuration": 0.28,
        "generatedDuration": 0.28,
        "source": "hyena/growl/growl_sample_23.wav",
        "playbackGainDb": 27.019
      },
      {
        "id": "hyena-snore-1070",
        "label": "Snore",
        "prompt": "The non-vocal sound is produced as a sleeping spotted hyena rests.",
        "realAudio": "audio/hyena-snore-1070-real.wav",
        "generatedAudio": "audio/hyena-snore-1070-generated.wav",
        "realSpectrogram": "spectrograms/hyena-snore-1070-real.png",
        "generatedSpectrogram": "spectrograms/hyena-snore-1070-generated.png",
        "duration": 0.97,
        "realDuration": 0.97,
        "generatedDuration": 0.97,
        "source": "hyena/snore/snore_sample_1070.wav",
        "playbackGainDb": 45.302
      },
      {
        "id": "hyena-squeal-1582",
        "label": "Squeal",
        "prompt": "A vocal sound is produced when a spotted hyena is bitten in conflict.",
        "realAudio": "audio/hyena-squeal-1582-real.wav",
        "generatedAudio": "audio/hyena-squeal-1582-generated.wav",
        "realSpectrogram": "spectrograms/hyena-squeal-1582-real.png",
        "generatedSpectrogram": "spectrograms/hyena-squeal-1582-generated.png",
        "duration": 0.35,
        "realDuration": 0.35,
        "generatedDuration": 0.35,
        "source": "hyena/squeal/squeal_sample_1582.wav",
        "playbackGainDb": 32.364
      },
      {
        "id": "hyena-squitter-769",
        "label": "Squitter",
        "prompt": "The animal sound is heard when a spotted hyena cub stays near its mother.",
        "realAudio": "audio/hyena-squitter-769-real.wav",
        "generatedAudio": "audio/hyena-squitter-769-generated.wav",
        "realSpectrogram": "spectrograms/hyena-squitter-769-real.png",
        "generatedSpectrogram": "spectrograms/hyena-squitter-769-generated.png",
        "duration": 0.7,
        "realDuration": 0.7,
        "generatedDuration": 0.7,
        "source": "hyena/squitter/squitter_sample_769.wav",
        "playbackGainDb": 40.99
      }
    ]
  },
  "meerkat": {
    "name": "Meerkat",
    "samples": [
      {
        "id": "meerkat-alarm-call-303",
        "label": "Alarm call",
        "prompt": "A vocal sound is audible while a meerkat watches for a predator.",
        "realAudio": "audio/meerkat-alarm-call-303-real.wav",
        "generatedAudio": "audio/meerkat-alarm-call-303-generated.wav",
        "realSpectrogram": "spectrograms/meerkat-alarm-call-303-real.png",
        "generatedSpectrogram": "spectrograms/meerkat-alarm-call-303-generated.png",
        "duration": 0.2291,
        "realDuration": 0.2291,
        "generatedDuration": 0.2291,
        "source": "meerkat/alarm_call/alarm_call_sample_303.wav",
        "playbackGainDb": 14.937
      },
      {
        "id": "meerkat-aggressive-call-786",
        "label": "Aggressive call",
        "prompt": "The call is heard from a meerkat as meerkats clash during a hostile interaction.",
        "realAudio": "audio/meerkat-aggressive-call-786-real.wav",
        "generatedAudio": "audio/meerkat-aggressive-call-786-generated.wav",
        "realSpectrogram": "spectrograms/meerkat-aggressive-call-786-real.png",
        "generatedSpectrogram": "spectrograms/meerkat-aggressive-call-786-generated.png",
        "duration": 0.286,
        "realDuration": 0.286,
        "generatedDuration": 0.286,
        "source": "meerkat/aggressive_call/aggressive_call_sample_786.wav",
        "playbackGainDb": 4.135
      },
      {
        "id": "meerkat-close-call-18",
        "label": "Close call",
        "prompt": "A vocal sound occurs as a meerkat forages with limited visual contact.",
        "realAudio": "audio/meerkat-close-call-18-real.wav",
        "generatedAudio": "audio/meerkat-close-call-18-generated.wav",
        "realSpectrogram": "spectrograms/meerkat-close-call-18-real.png",
        "generatedSpectrogram": "spectrograms/meerkat-close-call-18-generated.png",
        "duration": 0.2241,
        "realDuration": 0.2241,
        "generatedDuration": 0.2241,
        "source": "meerkat/close_call/close_call_sample_18.wav",
        "playbackGainDb": 13.057
      },
      {
        "id": "meerkat-lead-call-120",
        "label": "Lead call",
        "prompt": "A sound is heard while a meerkat moves ahead of the group.",
        "realAudio": "audio/meerkat-lead-call-120-real.wav",
        "generatedAudio": "audio/meerkat-lead-call-120-generated.wav",
        "realSpectrogram": "spectrograms/meerkat-lead-call-120-real.png",
        "generatedSpectrogram": "spectrograms/meerkat-lead-call-120-generated.png",
        "duration": 0.3401,
        "realDuration": 0.3401,
        "generatedDuration": 0.3401,
        "source": "meerkat/lead_call/lead_call_sample_120.wav",
        "playbackGainDb": 9.311
      },
      {
        "id": "meerkat-move-call-788",
        "label": "Move call",
        "prompt": "The animal sound is audible when a foraging meerkat initiates a movement sequence.",
        "realAudio": "audio/meerkat-move-call-788-real.wav",
        "generatedAudio": "audio/meerkat-move-call-788-generated.wav",
        "realSpectrogram": "spectrograms/meerkat-move-call-788-real.png",
        "generatedSpectrogram": "spectrograms/meerkat-move-call-788-generated.png",
        "duration": 0.2401,
        "realDuration": 0.2401,
        "generatedDuration": 0.2401,
        "source": "meerkat/move_call/move_call_sample_788.wav",
        "playbackGainDb": 11.379
      },
      {
        "id": "meerkat-social-call-65",
        "label": "Social call",
        "prompt": "A vocal sound is audible when a meerkat pup solicits food from adults.",
        "realAudio": "audio/meerkat-social-call-65-real.wav",
        "generatedAudio": "audio/meerkat-social-call-65-generated.wav",
        "realSpectrogram": "spectrograms/meerkat-social-call-65-real.png",
        "generatedSpectrogram": "spectrograms/meerkat-social-call-65-generated.png",
        "duration": 0.382,
        "realDuration": 0.382,
        "generatedDuration": 0.382,
        "source": "meerkat/social_call/social_call_sample_65.wav",
        "playbackGainDb": 10.236
      }
    ]
  },
  "marmoset": {
    "name": "Common marmoset",
    "samples": [
      {
        "id": "marmoset-phee-204",
        "label": "Phee",
        "prompt": "An audible sound is heard while a marmoset reaches conspecifics outside sight.",
        "realAudio": "audio/marmoset-phee-204-real.wav",
        "generatedAudio": "audio/marmoset-phee-204-generated.wav",
        "realSpectrogram": "spectrograms/marmoset-phee-204-real.png",
        "generatedSpectrogram": "spectrograms/marmoset-phee-204-generated.png",
        "duration": 1.85,
        "realDuration": 1.85,
        "generatedDuration": 1.85,
        "source": "marmoset/Phee/Phee_sample_204.wav",
        "playbackGainDb": 0.805
      },
      {
        "id": "marmoset-infant-829",
        "label": "Infant",
        "prompt": "The animal sound comes from an infant marmoset while it remains alone.",
        "realAudio": "audio/marmoset-infant-829-real.wav",
        "generatedAudio": "audio/marmoset-infant-829-generated.wav",
        "realSpectrogram": "spectrograms/marmoset-infant-829-real.png",
        "generatedSpectrogram": "spectrograms/marmoset-infant-829-generated.png",
        "duration": 0.9,
        "realDuration": 0.9,
        "generatedDuration": 0.9,
        "source": "marmoset/Infant/Infant_sample_829.wav",
        "playbackGainDb": 11.109
      },
      {
        "id": "marmoset-seep-390",
        "label": "Seep",
        "prompt": "A vocalization occurs while a marmoset notices a sudden threat.",
        "realAudio": "audio/marmoset-seep-390-real.wav",
        "generatedAudio": "audio/marmoset-seep-390-generated.wav",
        "realSpectrogram": "spectrograms/marmoset-seep-390-real.png",
        "generatedSpectrogram": "spectrograms/marmoset-seep-390-generated.png",
        "duration": 0.7,
        "realDuration": 0.7,
        "generatedDuration": 0.7,
        "source": "marmoset/Seep/Seep_sample_390.wav",
        "playbackGainDb": 15.506
      },
      {
        "id": "marmoset-trill-532",
        "label": "Trill",
        "prompt": "The audible sound is produced when marmosets keep short-range contact.",
        "realAudio": "audio/marmoset-trill-532-real.wav",
        "generatedAudio": "audio/marmoset-trill-532-generated.wav",
        "realSpectrogram": "spectrograms/marmoset-trill-532-real.png",
        "generatedSpectrogram": "spectrograms/marmoset-trill-532-generated.png",
        "duration": 1.05,
        "realDuration": 1.05,
        "generatedDuration": 1.05,
        "source": "marmoset/Trill/Trill_sample_532.wav",
        "playbackGainDb": 19.35
      },
      {
        "id": "marmoset-tsik-579",
        "label": "Tsik",
        "prompt": "An animal sound is produced while marmosets gather near a threat.",
        "realAudio": "audio/marmoset-tsik-579-real.wav",
        "generatedAudio": "audio/marmoset-tsik-579-generated.wav",
        "realSpectrogram": "spectrograms/marmoset-tsik-579-real.png",
        "generatedSpectrogram": "spectrograms/marmoset-tsik-579-generated.png",
        "duration": 0.75,
        "realDuration": 0.75,
        "generatedDuration": 0.75,
        "source": "marmoset/Tsik/Tsik_sample_579.wav",
        "playbackGainDb": 16.824
      },
      {
        "id": "marmoset-twitter-320",
        "label": "Twitter",
        "prompt": "The call occurs when two or more marmosets exchange contact.",
        "realAudio": "audio/marmoset-twitter-320-real.wav",
        "generatedAudio": "audio/marmoset-twitter-320-generated.wav",
        "realSpectrogram": "spectrograms/marmoset-twitter-320-real.png",
        "generatedSpectrogram": "spectrograms/marmoset-twitter-320-generated.png",
        "duration": 1.35,
        "realDuration": 1.35,
        "generatedDuration": 1.35,
        "source": "marmoset/Twitter/Twitter_sample_320.wav",
        "playbackGainDb": 14.494
      }
    ]
  },
  "goat": {
    "name": "Domestic goat",
    "samples": [
      {
        "id": "goat-mother-kid-reunion-383",
        "label": "Mother–kid reunion",
        "prompt": "A vocal sound is produced while a goat kid reaches its mother goat after separation.",
        "realAudio": "audio/goat-mother-kid-reunion-383-real.wav",
        "generatedAudio": "audio/goat-mother-kid-reunion-383-generated.wav",
        "realSpectrogram": "spectrograms/goat-mother-kid-reunion-383-real.png",
        "generatedSpectrogram": "spectrograms/goat-mother-kid-reunion-383-generated.png",
        "duration": 2.0,
        "realDuration": 2.0,
        "generatedDuration": 2.0,
        "source": "goat/Mother-kid reunion/Mother-kid reunion_sample_383.wav",
        "playbackGainDb": 12.158
      },
      {
        "id": "goat-feed-distribution-239",
        "label": "Feed distribution",
        "prompt": "The call occurs while a herd goat moves near provided food.",
        "realAudio": "audio/goat-feed-distribution-239-real.wav",
        "generatedAudio": "audio/goat-feed-distribution-239-generated.wav",
        "realSpectrogram": "spectrograms/goat-feed-distribution-239-real.png",
        "generatedSpectrogram": "spectrograms/goat-feed-distribution-239-generated.png",
        "duration": 2.0,
        "realDuration": 2.0,
        "generatedDuration": 2.0,
        "source": "goat/Feed distribution/Feed distribution_sample_239.wav",
        "playbackGainDb": 10.82
      },
      {
        "id": "goat-heat-399",
        "label": "Heat",
        "prompt": "An animal sound comes from a goat while it displays reproductive-cycle signs.",
        "realAudio": "audio/goat-heat-399-real.wav",
        "generatedAudio": "audio/goat-heat-399-generated.wav",
        "realSpectrogram": "spectrograms/goat-heat-399-real.png",
        "generatedSpectrogram": "spectrograms/goat-heat-399-generated.png",
        "duration": 2.0,
        "realDuration": 2.0,
        "generatedDuration": 2.0,
        "source": "goat/Heat/Heat_sample_399.wav",
        "playbackGainDb": 2.746
      },
      {
        "id": "goat-injury-or-death-154",
        "label": "Injury or death",
        "prompt": "An audible sound comes from a herd goat as a goat reacts after an injury.",
        "realAudio": "audio/goat-injury-or-death-154-real.wav",
        "generatedAudio": "audio/goat-injury-or-death-154-generated.wav",
        "realSpectrogram": "spectrograms/goat-injury-or-death-154-real.png",
        "generatedSpectrogram": "spectrograms/goat-injury-or-death-154-generated.png",
        "duration": 2.0,
        "realDuration": 2.0,
        "generatedDuration": 2.0,
        "source": "goat/Injury or death/Injury or death_sample_154.wav",
        "playbackGainDb": 10.368
      },
      {
        "id": "goat-mother-kid-separation-64",
        "label": "Mother–kid separation",
        "prompt": "An animal sound is produced as a goat kid waits away from its mother goat.",
        "realAudio": "audio/goat-mother-kid-separation-64-real.wav",
        "generatedAudio": "audio/goat-mother-kid-separation-64-generated.wav",
        "realSpectrogram": "spectrograms/goat-mother-kid-separation-64-real.png",
        "generatedSpectrogram": "spectrograms/goat-mother-kid-separation-64-generated.png",
        "duration": 2.0,
        "realDuration": 2.0,
        "generatedDuration": 2.0,
        "source": "goat/Mother-kid separation/Mother-kid separation_sample_64.wav",
        "playbackGainDb": 12.584
      },
      {
        "id": "goat-parturition-278",
        "label": "Parturition",
        "prompt": "A vocalization is heard from a mother goat while it gives birth to a kid.",
        "realAudio": "audio/goat-parturition-278-real.wav",
        "generatedAudio": "audio/goat-parturition-278-generated.wav",
        "realSpectrogram": "spectrograms/goat-parturition-278-real.png",
        "generatedSpectrogram": "spectrograms/goat-parturition-278-generated.png",
        "duration": 2.0,
        "realDuration": 2.0,
        "generatedDuration": 2.0,
        "source": "goat/Parturition/Parturition_sample_278.wav",
        "playbackGainDb": 4.379
      },
      {
        "id": "goat-presence-of-unknown-visitors-88",
        "label": "Presence of unknown visitors",
        "prompt": "An audible sound is heard when a goat turns toward an unfamiliar presence.",
        "realAudio": "audio/goat-presence-of-unknown-visitors-88-real.wav",
        "generatedAudio": "audio/goat-presence-of-unknown-visitors-88-generated.wav",
        "realSpectrogram": "spectrograms/goat-presence-of-unknown-visitors-88-real.png",
        "generatedSpectrogram": "spectrograms/goat-presence-of-unknown-visitors-88-generated.png",
        "duration": 2.0,
        "realDuration": 2.0,
        "generatedDuration": 2.0,
        "source": "goat/Presence of unknown visitors/Presence of unknown visitors_sample_88.wav",
        "playbackGainDb": 8.822
      },
      {
        "id": "goat-social-isolation-99",
        "label": "Social isolation",
        "prompt": "A vocal sound occurs while a separated goat stands away from herd members.",
        "realAudio": "audio/goat-social-isolation-99-real.wav",
        "generatedAudio": "audio/goat-social-isolation-99-generated.wav",
        "realSpectrogram": "spectrograms/goat-social-isolation-99-real.png",
        "generatedSpectrogram": "spectrograms/goat-social-isolation-99-generated.png",
        "duration": 2.0,
        "realDuration": 2.0,
        "generatedDuration": 2.0,
        "source": "goat/Social isolation/Social isolation_sample_99.wav",
        "playbackGainDb": 10.237
      }
    ]
  },
  "zebra": {
    "name": "Plains zebra",
    "samples": [
      {
        "id": "zebra-quagga-quagga-94",
        "label": "Quagga quagga",
        "prompt": "A vocal sound is produced when a separated plains zebra seeks contact.",
        "realAudio": "audio/zebra-quagga-quagga-94-real.wav",
        "generatedAudio": "audio/zebra-quagga-quagga-94-generated.wav",
        "realSpectrogram": "spectrograms/zebra-quagga-quagga-94-real.png",
        "generatedSpectrogram": "spectrograms/zebra-quagga-quagga-94-generated.png",
        "duration": 0.658,
        "realDuration": 0.658,
        "generatedDuration": 0.658,
        "source": "zebra/quagga quagga/quagga quagga_sample_94.wav",
        "playbackGainDb": 15.439
      },
      {
        "id": "zebra-snort-153",
        "label": "Snort",
        "prompt": "The animal sound is heard while a plains zebra stands and shifts posture.",
        "realAudio": "audio/zebra-snort-153-real.wav",
        "generatedAudio": "audio/zebra-snort-153-generated.wav",
        "realSpectrogram": "spectrograms/zebra-snort-153-real.png",
        "generatedSpectrogram": "spectrograms/zebra-snort-153-generated.png",
        "duration": 0.3261,
        "realDuration": 0.3261,
        "generatedDuration": 0.3261,
        "source": "zebra/snort/snort_sample_153.wav",
        "playbackGainDb": 17.26
      },
      {
        "id": "zebra-soft-snort-162",
        "label": "Soft snort",
        "prompt": "A vocal sound comes from a plains zebra as it stands near other plains zebras.",
        "realAudio": "audio/zebra-soft-snort-162-real.wav",
        "generatedAudio": "audio/zebra-soft-snort-162-generated.wav",
        "realSpectrogram": "spectrograms/zebra-soft-snort-162-real.png",
        "generatedSpectrogram": "spectrograms/zebra-soft-snort-162-generated.png",
        "duration": 0.2332,
        "realDuration": 0.2332,
        "generatedDuration": 0.2332,
        "source": "zebra/soft snort/soft snort_sample_162.wav",
        "playbackGainDb": 14.956
      },
      {
        "id": "zebra-squeal-132",
        "label": "Squeal",
        "prompt": "An animal sound is heard as plains zebras meet during a close interaction.",
        "realAudio": "audio/zebra-squeal-132-real.wav",
        "generatedAudio": "audio/zebra-squeal-132-generated.wav",
        "realSpectrogram": "spectrograms/zebra-squeal-132-real.png",
        "generatedSpectrogram": "spectrograms/zebra-squeal-132-generated.png",
        "duration": 0.1032,
        "realDuration": 0.1032,
        "generatedDuration": 0.1032,
        "source": "zebra/squeal/squeal_sample_132.wav",
        "playbackGainDb": 14.613
      }
    ]
  },
  "zebra-finch": {
    "name": "Zebra finch",
    "samples": [
      {
        "id": "zebra-finch-song-84",
        "label": "Song",
        "prompt": "An animal sound comes from an adult male zebra finch as it performs courtship.",
        "realAudio": "audio/zebra-finch-song-84-real.wav",
        "generatedAudio": "audio/zebra-finch-song-84-generated.wav",
        "realSpectrogram": "spectrograms/zebra-finch-song-84-real.png",
        "generatedSpectrogram": "spectrograms/zebra-finch-song-84-generated.png",
        "duration": 2.7909,
        "realDuration": 2.7909,
        "generatedDuration": 2.7909,
        "source": "zebrafinch/song/song_sample_84.wav",
        "playbackGainDb": 9.169
      },
      {
        "id": "zebra-finch-aggressive-call-12",
        "label": "Aggressive call",
        "prompt": "An animal sound is audible when a zebra finch threatens another individual.",
        "realAudio": "audio/zebra-finch-aggressive-call-12-real.wav",
        "generatedAudio": "audio/zebra-finch-aggressive-call-12-generated.wav",
        "realSpectrogram": "spectrograms/zebra-finch-aggressive-call-12-real.png",
        "generatedSpectrogram": "spectrograms/zebra-finch-aggressive-call-12-generated.png",
        "duration": 0.2113,
        "realDuration": 0.2113,
        "generatedDuration": 0.2113,
        "source": "zebrafinch/aggressive call/aggressive call_sample_12.wav",
        "playbackGainDb": 5.848
      },
      {
        "id": "zebra-finch-begging-call-20",
        "label": "Begging call",
        "prompt": "A vocal sound is heard from a zebra finch chick or fledgling as a fledgling zebra finch asks for food.",
        "realAudio": "audio/zebra-finch-begging-call-20-real.wav",
        "generatedAudio": "audio/zebra-finch-begging-call-20-generated.wav",
        "realSpectrogram": "spectrograms/zebra-finch-begging-call-20-real.png",
        "generatedSpectrogram": "spectrograms/zebra-finch-begging-call-20-generated.png",
        "duration": 0.7051,
        "realDuration": 0.7051,
        "generatedDuration": 0.7051,
        "source": "zebrafinch/begging call/begging call_sample_20.wav",
        "playbackGainDb": 18.611
      },
      {
        "id": "zebra-finch-distance-call-515",
        "label": "Distance call",
        "prompt": "A vocalization occurs while a zebra finch reaches group members outside sight.",
        "realAudio": "audio/zebra-finch-distance-call-515-real.wav",
        "generatedAudio": "audio/zebra-finch-distance-call-515-generated.wav",
        "realSpectrogram": "spectrograms/zebra-finch-distance-call-515-real.png",
        "generatedSpectrogram": "spectrograms/zebra-finch-distance-call-515-generated.png",
        "duration": 0.4553,
        "realDuration": 0.4553,
        "generatedDuration": 0.4553,
        "source": "zebrafinch/distance call/distance call_sample_515.wav",
        "playbackGainDb": 1.678
      },
      {
        "id": "zebra-finch-long-tonal-call-103",
        "label": "Long tonal call",
        "prompt": "A vocal sound occurs as a fledgling zebra finch contacts its parents.",
        "realAudio": "audio/zebra-finch-long-tonal-call-103-real.wav",
        "generatedAudio": "audio/zebra-finch-long-tonal-call-103-generated.wav",
        "realSpectrogram": "spectrograms/zebra-finch-long-tonal-call-103-real.png",
        "generatedSpectrogram": "spectrograms/zebra-finch-long-tonal-call-103-generated.png",
        "duration": 0.2232,
        "realDuration": 0.2232,
        "generatedDuration": 0.2232,
        "source": "zebrafinch/long tonal call/long tonal call_sample_103.wav",
        "playbackGainDb": 36.654
      },
      {
        "id": "zebra-finch-nest-call-327",
        "label": "Nest call",
        "prompt": "An animal sound occurs when paired zebra finches relay at the nest.",
        "realAudio": "audio/zebra-finch-nest-call-327-real.wav",
        "generatedAudio": "audio/zebra-finch-nest-call-327-generated.wav",
        "realSpectrogram": "spectrograms/zebra-finch-nest-call-327-real.png",
        "generatedSpectrogram": "spectrograms/zebra-finch-nest-call-327-generated.png",
        "duration": 0.108,
        "realDuration": 0.108,
        "generatedDuration": 0.108,
        "source": "zebrafinch/nest call/nest call_sample_327.wav",
        "playbackGainDb": 24.799
      },
      {
        "id": "zebra-finch-tet-call-183",
        "label": "Tet call",
        "prompt": "A vocal sound is produced when adult zebra finches interact during neutral contact.",
        "realAudio": "audio/zebra-finch-tet-call-183-real.wav",
        "generatedAudio": "audio/zebra-finch-tet-call-183-generated.wav",
        "realSpectrogram": "spectrograms/zebra-finch-tet-call-183-real.png",
        "generatedSpectrogram": "spectrograms/zebra-finch-tet-call-183-generated.png",
        "duration": 0.1299,
        "realDuration": 0.1299,
        "generatedDuration": 0.1299,
        "source": "zebrafinch/tet call/tet call_sample_183.wav",
        "playbackGainDb": 21.919
      },
      {
        "id": "zebra-finch-thuk-call-44",
        "label": "Thuk call",
        "prompt": "A vocal sound is heard from a parent zebra finch as it parent reacts near chicks.",
        "realAudio": "audio/zebra-finch-thuk-call-44-real.wav",
        "generatedAudio": "audio/zebra-finch-thuk-call-44-generated.wav",
        "realSpectrogram": "spectrograms/zebra-finch-thuk-call-44-real.png",
        "generatedSpectrogram": "spectrograms/zebra-finch-thuk-call-44-generated.png",
        "duration": 0.0606,
        "realDuration": 0.0606,
        "generatedDuration": 0.0606,
        "source": "zebrafinch/thuk call/thuk call_sample_44.wav",
        "playbackGainDb": 10.741
      },
      {
        "id": "zebra-finch-tuck-call-77",
        "label": "Tuck call",
        "prompt": "An animal sound is heard from an adult zebra finch while it reacts to possible danger.",
        "realAudio": "audio/zebra-finch-tuck-call-77-real.wav",
        "generatedAudio": "audio/zebra-finch-tuck-call-77-generated.wav",
        "realSpectrogram": "spectrograms/zebra-finch-tuck-call-77-real.png",
        "generatedSpectrogram": "spectrograms/zebra-finch-tuck-call-77-generated.png",
        "duration": 0.0463,
        "realDuration": 0.0463,
        "generatedDuration": 0.0463,
        "source": "zebrafinch/tuck call/tuck call_sample_77.wav",
        "playbackGainDb": 26.743
      },
      {
        "id": "zebra-finch-whine-call-54",
        "label": "Whine call",
        "prompt": "A call is produced as zebra finch mates relay around the nest.",
        "realAudio": "audio/zebra-finch-whine-call-54-real.wav",
        "generatedAudio": "audio/zebra-finch-whine-call-54-generated.wav",
        "realSpectrogram": "spectrograms/zebra-finch-whine-call-54-real.png",
        "generatedSpectrogram": "spectrograms/zebra-finch-whine-call-54-generated.png",
        "duration": 0.1552,
        "realDuration": 0.1552,
        "generatedDuration": 0.1552,
        "source": "zebrafinch/whine call/whine call_sample_54.wav",
        "playbackGainDb": 27.909
      }
    ]
  }
};
